/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import models.ItemBarang;

/**
 *
 * @author Chandra
 */
public class VKelolaHutangForm extends javax.swing.JFrame {

    VKasir vKasir = VKasir.getInstance();
    private String satuanId;
    private int tipeForm;
    private Map<String, String> map;

    /**
     * Creates new form VKasir
     */
    public VKelolaHutangForm() {
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.createImage(vKasir.getLogo());
        setIconImage(img);
             
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VKelolaBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VKelolaBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VKelolaBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VKelolaBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        initComponents();
        
        this.setTitle(vKasir.getAppConfig()
                .getConfig("APP_NAME")+" - Bayar Hutang");
        
        //        set color
        jPanel2.setBackground(
                Color.decode(vKasir.getAppConfig().getConfig("APP_MAIN_COLOR")));
        tfTotal.addActionListener(tfEnterKey);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNamaBarang = new javax.swing.JTextField();
        jlHargaBeli = new javax.swing.JLabel();
        jbTombol = new javax.swing.JButton();
        tfTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("NAMA CUSTOMER");

        tfNamaBarang.setEditable(false);
        tfNamaBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlHargaBeli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlHargaBeli.setText("TOTAL (Rp.)");

        jbTombol.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbTombol.setText("BAYAR");
        jbTombol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbTombolMouseClicked(evt);
            }
        });
        jbTombol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTombolActionPerformed(evt);
            }
        });

        tfTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(tfNamaBarang)
                    .addComponent(jlHargaBeli)
                    .addComponent(jbTombol, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(tfTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlHargaBeli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbTombol)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        tfNamaBarang.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbTombolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbTombolMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbTombolMouseClicked

    private void jbTombolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTombolActionPerformed
        // TODO add your handling code here:
        bayar();
    }//GEN-LAST:event_jbTombolActionPerformed

    public void setTfNamaBarang(String text) {
        tfNamaBarang.setText(text);
    }

    public void setTfHargaJual(String text) {
        tfTotal.setText(text);
    }

    public void setType(int type) {
        this.tipeForm = type;
        if (type == 1) {
            this.setTitle("TANI JAYA - Tambah Barang");
            jbTombol.setText("TAMBAH");
        } else {
            this.setTitle("TANI JAYA - Edit Barang");
            jbTombol.setText("UPDATE");
        }
    }

    public void bayar() {
        VKelolaHutang vKelolaHutang = vKasir.getKelolaHutang();
        String isLunas = "0";
        int hutangJml = 0;
        int uangDiserahkan = 0;

//        Bandingkan harga apakah jika ditambah akan lunas
        java.sql.ResultSet rs;
        java.sql.Connection conn = vKasir.getDBConn();
        java.sql.PreparedStatement ps;
        try {
            ps = conn.prepareStatement("SELECT "
                    + "id, pelanggan, total, uang_diserahkan"
                    + " FROM transaksi"
                    + " WHERE transaksi.id = '" + vKelolaHutang.getSelectedRowId() + "' "
            );
            rs = ps.executeQuery();

            while (rs.next()) {
                hutangJml = (int) Math.round(
                        Double.parseDouble(rs.getString("total"))
                        - Double.parseDouble(rs.getString("uang_diserahkan"))
                );

                uangDiserahkan
                        = (int) Math.round(Double.parseDouble(rs.getString("uang_diserahkan"))
                                + Integer.parseInt(tfTotal.getText()));
            }

            if (uangDiserahkan >= hutangJml) {
                isLunas = "0";
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        java.sql.PreparedStatement ps2;
        try {
            ps2 = conn.prepareStatement("UPDATE "
                    + " transaksi"
                    + " SET is_hutang = " + isLunas + ""
                    + ", uang_diserahkan = " + uangDiserahkan + ""
                    + " WHERE id = '" + vKelolaHutang.getSelectedRowId() + "' "
            );

            ps2.executeUpdate();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
        try {
            vKelolaHutang.getData("");
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "Pembayaran Berhasil!");
        this.setVisible(false);
    }

    Action tfEnterKey = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            bayar();
        }
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbTombol;
    private javax.swing.JLabel jlHargaBeli;
    private javax.swing.JTextField tfNamaBarang;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
