/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import models.ItemBarang;

/**
 *
 * @author Chandra
 */
public class VKelolaBarangForm extends javax.swing.JFrame {

    VKasir vKasir = VKasir.getInstance();
    private String satuanId;
    private int tipeForm;
    private Map<String, String> map;

    /**
     * Creates new form VKasir
     */
    public VKelolaBarangForm(int type) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VKelolaBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VKelolaBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VKelolaBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VKelolaBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        initComponents();
        this.tipeForm = type;
        if (type == 1) {
            this.setTitle("TANI JAYA - Tambah Barang");
            jbTombol.setText("TAMBAH");
        } else {
            this.setTitle("TANI JAYA - Edit Barang");
            jbTombol.setText("UPDATE");
        }

        cbSatuan.removeAllItems(); //digunakan untuk membersihkan item jcombobox sebelum diisi.
        setCbSatuan();
    }

    public void setCbSatuan() {
        try {
            java.sql.ResultSet rs;
            java.sql.Connection conn = vKasir.getDBConn();
            java.sql.PreparedStatement ps = conn.prepareStatement("SELECT id, satuan FROM satuan");
            rs = ps.executeQuery();

            models.ItemBarang ib;

            while (rs.next()) {
                ib = new models.ItemBarang(rs.getString(1), rs.getString(2));
//                itemBarangs.add(ib);
                System.out.println(rs.getString(1) + " " + rs.getString(2));
                cbSatuan.addItem(ib);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR load satuan " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNamaBarang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jlHargaBeli = new javax.swing.JLabel();
        tfHargaBeli = new javax.swing.JTextField();
        jbTombol = new javax.swing.JButton();
        tfKode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbSatuan = new javax.swing.JComboBox<>();
        tfHargaJual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("NAMA BARANG");

        tfNamaBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("SATUAN");

        jlHargaBeli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlHargaBeli.setText("HARGA MODAL (Rp.)");

        tfHargaBeli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jbTombol.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbTombol.setText("TAMBAH");
        jbTombol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbTombolMouseClicked(evt);
            }
        });

        tfKode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("KODE (Optional)");

        cbSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSatuanActionPerformed(evt);
            }
        });

        tfHargaJual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("HARGA JUAL (Rp.)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(tfNamaBarang)
                    .addComponent(jLabel2)
                    .addComponent(jlHargaBeli)
                    .addComponent(tfHargaBeli)
                    .addComponent(jbTombol, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(tfKode)
                    .addComponent(cbSatuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(tfHargaJual))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jlHargaBeli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbTombol)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tfNamaBarang.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbTombolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbTombolMouseClicked
        // TODO add your handling code here:
        try {
            VKelolaBarang vKelolaBarang = vKasir.getKelolaBarang();

            if (this.tipeForm == 1) { //tambah
                String sql
                        = "insert into barang "
                        + "(nama, satuan_id, harga_beli, harga_jual,kode) values('"
                        + tfNamaBarang.getText() + "','" + satuanId + "','"
                        + tfHargaBeli.getText() + "','" + tfHargaJual.getText()
                        + "','" + tfKode.getText() + "')";

                java.sql.Connection conn = vKasir.getDBConn();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();

                JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            } else {
                java.sql.Connection conn = vKasir.getDBConn();
                java.sql.PreparedStatement ps = conn.prepareStatement("UPDATE "
                        + " barang"
                        + " SET NAMA = '" + tfNamaBarang.getText() + "'"
                        + ", satuan_id = '" + satuanId + "'"
                        + ", harga_beli = '" + tfHargaBeli.getText() + "'"
                        + ", harga_jual = '" + tfHargaJual.getText() + "'"
                        + ", kode = '" + tfKode.getText() + "'"
                        + " WHERE id = '" + vKelolaBarang.getSelectedRowId() + "' "
                );
                ps.executeUpdate();
            }

            tfNamaBarang.setText("");
            tfHargaBeli.setText("");
            tfHargaJual.setText("");
            tfKode.setText("");

            vKelolaBarang.getData("");

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbTombolMouseClicked

    private void cbSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSatuanActionPerformed
        // TODO add your handling code here:
        Object item = cbSatuan.getSelectedItem();
        String value = ((models.ItemBarang) item).getId();
        satuanId = value;
        System.out.println(value);
    }//GEN-LAST:event_cbSatuanActionPerformed

    public void setTfNamaBarang(String text) {
        tfNamaBarang.setText(text);
    }

    public void setTfHargaBeli(String text) {
        tfHargaBeli.setText(text);
    }

    public void setTfHargaJual(String text) {
        tfHargaJual.setText(text);
    }

    public void setTfKode(String text) {
        tfKode.setText(text);
    }

    public void setCbSatuan(ItemBarang itemBarang) {
        int cbSize = cbSatuan.getItemCount();

        for (int i = 0; i < cbSize; i++) {
            models.ItemBarang isi = cbSatuan.getItemAt(i);

//            bandingkan isinya
            if (isi.equals(itemBarang)) {
                System.out.println("bener");
                cbSatuan.setSelectedIndex(i);
            }
        }
    }

    public void setType(int type) {
        this.tipeForm = type;
        if (type == 1) {
            this.setTitle("TANI JAYA - Tambah Barang");
            jbTombol.setText("TAMBAH");
        } else {
            this.setTitle("TANI JAYA - Edit Barang");
            jbTombol.setText("UPDATE");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<models.ItemBarang> cbSatuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbTombol;
    private javax.swing.JLabel jlHargaBeli;
    private javax.swing.JTextField tfHargaBeli;
    private javax.swing.JTextField tfHargaJual;
    private javax.swing.JTextField tfKode;
    private javax.swing.JTextField tfNamaBarang;
    // End of variables declaration//GEN-END:variables
}
